Finalizer + Tests
wasmCloud/wasmcloud-k8s-operator pull request #4
Opened 2021-09-16 15:39 UTC by alsuren

WIP on finalizer and tests

The current plan is to assume that we have `nats-server` running for integration tests, and set up the equivalent of `nats reply wasmbus.alc.default.* {"status":"received"}` (probably reimplemented in Go) before each test. If this doesn't work out for us, we could add an interface to the lattice_client module, and pass in a mock nats client for our tests.

2021-09-16 15:46 UTC, StuartHarris requested changes

2021-09-16 15:46 UTC, StuartHarris commented on lattice_client/lattice_client.go
> +	r, e := c.send("delete", app)
I got the impression from Kevin that the topic suffixes are `.put` and `.del`

2021-09-21 11:46 UTC, attriaayush approved these changes

2021-09-22 08:35 UTC, StuartHarris approved these changes

2021-09-22 08:41 UTC, merged